// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgh2NQZYQ-DW7ZnFhJlw5D10IQ7f3JCoo',
    appId: '1:93683387744:web:d797f4c2d0f17e256b6205',
    messagingSenderId: '93683387744',
    projectId: 'noteapp-6afd9',
    authDomain: 'noteapp-6afd9.firebaseapp.com',
    storageBucket: 'noteapp-6afd9.firebasestorage.app',
    measurementId: 'G-1YXNX86Y8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIrzKc2xQ52cGXsKfWXEcpSryEW9KRFY',
    appId: '1:93683387744:android:57f91c651d5b2bd96b6205',
    messagingSenderId: '93683387744',
    projectId: 'noteapp-6afd9',
    storageBucket: 'noteapp-6afd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAzEjxgsh3hN-TMO-xUntMJoKLgtr9mO4',
    appId: '1:93683387744:ios:70e1778d0d8656db6b6205',
    messagingSenderId: '93683387744',
    projectId: 'noteapp-6afd9',
    storageBucket: 'noteapp-6afd9.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );
}
